# Generated by Django 4.2.3 on 2023-07-06 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_domain_registrar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domainprovider',
            old_name='is_delet',
            new_name='is_delete',
        ),
    ]
