# Generated by Django 4.2.3 on 2023-07-06 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_rename_is_delet_domainprovider_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='url',
            field=models.URLField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
