# Generated by Django 4.2.3 on 2023-07-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_domain_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='url',
            field=models.URLField(),
        ),
    ]
