# Generated by Django 4.2.3 on 2023-07-04 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
