# Generated by Django 4.2.3 on 2023-07-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_domain_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domainprovider',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='domainprovider',
            old_name='registrar',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ERP_ID',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='erp_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
