# Generated by Django 4.2.3 on 2023-07-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_rename_sub_name_subdomain_subdomain_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='Host',
            new_name='Registrar',
        ),
    ]
