# Generated by Django 3.2.12 on 2023-07-05 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_auto_20230705_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='expiry_date',
            new_name='certificate_expiry_date',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='IP_address',
        ),
        migrations.AddField(
            model_name='domain',
            name='domain_expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subdomain',
            name='certificate_expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subdomain',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subdomain',
            name='domain_expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
